### ISSUE TITLE
How to install in WAMP/MAMP

### ISSUE THREAD

**Issue by Louvivien** [mmilanovic4/mvc#1]
Hello, 
Thank you for this boilerplate. How do you install this in WAMP/MAMP ?
Thanks

**Comment by mmilanovic4** [comment]
Hello,

I have never used WAMP/MAMP, but I think you should follow these steps probably:

- Clone the project to your web server root directory (probably something like `C:\wamp\www`)
- Import database (`sys/db/dump.sql`) via phpmyadmin

Hope this helps. Cheers.
